# Generated by Django 3.1.7 on 2021-03-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sport_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=30, unique=True)),
                ('maximum_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('boarding_house', models.CharField(choices=[('TS', 'Tsavo'), ('TU', 'Turkana'), ('L', 'Laikipia'), ('B', 'Baringo'), ('S', 'Samburu')], max_length=30)),
                ('year_group', models.IntegerField(choices=[(9, 'Year Nine'), (10, 'Year Ten'), (11, 'Year Eleven'), (12, 'Year Twelve'), (13, 'Year Thirteen')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField()),
                ('sport_date', models.CharField(choices=[('M', 'Morning 6:30 AM'), ('E', 'Evening 8:30 PM')], max_length=30)),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sports')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
        ),
    ]
