# Generated by Django 3.1.7 on 2021-03-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
