# Generated by Django 3.1.7 on 2021-07-01 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=40)),
                ('maximum_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('boarding_house', models.CharField(choices=[('TS', 'Tsavo'), ('TU', 'Turkana'), ('L', 'Laikipia'), ('B', 'Baringo'), ('S', 'Samburu')], max_length=30)),
                ('year_group', models.IntegerField(choices=[(9, 'Year Nine'), (10, 'Year Ten'), (11, 'Year Eleven'), (12, 'Year Twelve'), (13, 'Year Thirteen')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=20)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altFrontend.eventtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altFrontend.eventinstance')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altFrontend.schedule'),
        ),
    ]
