# Generated by Django 3.1.7 on 2021-07-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altFrontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='year_group',
            field=models.IntegerField(choices=[(9, 'Year Nine'), (10, 'Year Ten'), (11, 'Year Eleven'), (12, 'Year Twelve'), (13, 'Year Thirteen')], default=13),
            preserve_default=False,
        ),
    ]
