# Generated by Django 3.1.7 on 2021-07-04 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('altFrontend', '0002_eventtemplate_year_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 7, 4, 19, 21, 58, 99284, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
