# Generated by Django 3.1.7 on 2021-07-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altFrontend', '0003_auto_20210704_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
    ]
