# Generated by Django 3.1.7 on 2021-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altFrontend', '0004_auto_20210711_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Wednesday', max_length=20),
        ),
    ]
