# Generated by Django 3.1.7 on 2021-08-08 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('altFrontend', '0005_auto_20210721_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.IntegerField()),
                ('event_date', models.DateTimeField()),
                ('registration_date', models.DateTimeField()),
                ('day', models.CharField(default='Sunday', max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('template_id', models.IntegerField()),
                ('schedule_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=40)),
                ('year_group', models.IntegerField()),
                ('maximum_capacity', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altFrontend.eventinstance')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
