# Generated by Django 4.1.12 on 2023-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altFrontend', '0008_alter_registrationrecord_day_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrecord',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
    ]
